// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_k-UrtgNemVYD3Sl4l04xZqx16_WHNaA',
    appId: '1:37062155962:web:1f6848580debf0ce186c83',
    messagingSenderId: '37062155962',
    projectId: 'the-flutter-123',
    authDomain: 'the-flutter-123.firebaseapp.com',
    storageBucket: 'the-flutter-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5h7akcPAQ7q513jbUAJ90oAC4co0nLJA',
    appId: '1:37062155962:android:23fc0fd1c3cec356186c83',
    messagingSenderId: '37062155962',
    projectId: 'the-flutter-123',
    storageBucket: 'the-flutter-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYg9-u3VdX66A-d-3t8SO7HlrhV_6dtDg',
    appId: '1:37062155962:ios:b78c4448e2af6917186c83',
    messagingSenderId: '37062155962',
    projectId: 'the-flutter-123',
    storageBucket: 'the-flutter-123.appspot.com',
    iosClientId: '37062155962-j1ctonoqme995qmk7q1u5vlblvt8fdlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYg9-u3VdX66A-d-3t8SO7HlrhV_6dtDg',
    appId: '1:37062155962:ios:f631c12aa028bab6186c83',
    messagingSenderId: '37062155962',
    projectId: 'the-flutter-123',
    storageBucket: 'the-flutter-123.appspot.com',
    iosClientId: '37062155962-ibi6v2hpnpeoq01hosq0dlq4hn4dvuem.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasecrud.RunnerTests',
  );
}
